Readme branch
PineappleApplePinecone/Taxi-service_Project pull request #1
Opened 2021-12-15 13:55 UTC by PineappleApplePinecone

2021-12-15 14:34 UTC, ChmokiMoki requested changes

2021-12-15 14:34 UTC, ChmokiMoki commented on README.md
> +###Taxi Service Project
```suggestion
### Taxi Service Project
```

2021-12-15 14:34 UTC, ChmokiMoki commented on README.md
> +####With this app you can:
```suggestion
#### With this app you can:
```

2021-12-15 14:34 UTC, ChmokiMoki commented on README.md
> +###Taxi Service Project
If you do not add a space, it will be displayed as `###Taxi Service Project`

2021-12-15 14:40 UTC, ChmokiMoki approved these changes

2021-12-15 14:54 UTC, Nick97-git requested changes
- remove redundant `/` from urls like /cars/, /drivers/, /manufacturers/
- DeleteCarController, DeleteDriverController, DeleteManufacturerController -> remove /all from /cars/all, /drivers/all, /manufacturers/all url patterns
- ConnectionUtil -> remove TIME_ZONE constant and in URL as value add stub

2021-12-15 14:54 UTC, Nick97-git commented on README.md
> +* Watch add/drivers page
rewrite it without using `Watch`

2021-12-15 14:54 UTC, Nick97-git commented on README.md
> +* Javax Servlet (v4.0.1)
```suggestion
* Servlet API (v4.0.1)
```

2021-12-15 14:54 UTC, Nick97-git commented on README.md
> +* Maven Checkstyle Plugin
remove this line

2021-12-15 14:54 UTC, Nick97-git commented on README.md
> +4. Cope and paste SQL schema from resources/init_db.sql in MySQL Workbench or terminal
```suggestion
4. Create schema in MySQL Workbench or terminal using resources/init_db.sql 
```

2021-12-16 06:57 UTC, Nick97-git requested changes
I don't see changes according to my comments not related to README

2021-12-16 06:57 UTC, Nick97-git commented on README.md
> +* Add/drivers page view
```suggestion
* Login
* Register new driver
```

2021-12-16 07:40 UTC, Nick97-git commented
what about these comments?
<img width="872" alt="Screenshot 2021-12-16 at 09 40 00" src="https://user-images.githubusercontent.com/60258373/146328604-9a5dbe9d-5dd8-423e-9776-bd9cf9f2a3d1.png">

2021-12-16 08:53 UTC, Nick97-git approved these changes

2021-12-16 08:53 UTC, Nick97-git commented on src/main/java/taxi/util/ConnectionUtil.java
> +    private static final String URL = "YOUR URL AND TIME ZONE";
```suggestion
    private static final String URL = "YOUR URL";
```

2022-01-04 09:07 UTC, merged